apiVersion: v1
kind: ServiceAccount
metadata:
  name: rethinkdb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rethinkdb
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rethinkdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rethinkdb
subjects:
  - kind: ServiceAccount
    name: rethinkdb
